export const Products = [
  {
    key: 0,
    producto: "pollera cargo",
    talle: "16",
    gender: "female",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    ganancia: 2000,
    vendidos: 11,
    fechaCreate:"01/03/2024",
    fechaUltmModificacion:"02/05/2024",
    estado: [{archivado: false, pocoStock: false}],
    owner: "graciela",
  },
  {
    key: 1,
    producto: "pantalon palazzo",
    talle: "XL",
    gender: "female",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    ganancia: 2000,
    vendidos: 11,
    fechaCreate:"01/03/2024",
    fechaUltmModificacion:"02/05/2024",
    estado: [{archivado: false, pocoStock: false}],
    owner: "graciela",
  },
  {
    key: 2,
    producto: "vestido fiesta",
    talle: "8",
    gender: "girl",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    ganancia: 2000,
    vendidos: 11,
    fechaCreate:"01/03/2024",
    fechaUltmModificacion:"02/05/2024",
    estado: [{archivado: false, pocoStock: false}],
    owner: "graciela",
  },
  
  
]

export const owner = [
  {
    id: 1,
    userName: "david",
    name: "Aramayo Wilber",
  },
]
