export const Products = [
  {
    key: 0,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    //fechaCreate:
    //fechaUltmModificacion:
    //estado: [archivado, pocoStock]
    owner: "",
  },
  {
    key: 1,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 2,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 3,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 4,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 5,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 6,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 7,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 8,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 9,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 10,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 11,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 12,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 13,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 14,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 15,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 16,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 17,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 18,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 19,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 20,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 21,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 22,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 23,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 24,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 25,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 26,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 27,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 28,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 29,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 30,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 31,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 32,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 33,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 34,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 35,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 36,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
  {
    key: 37,
    producto: "Jeans",
    talle: "16",
    gender: "hombre",
    category: "pantalon",
    stock: 88,
    stockMin: 0,
    precioVenta: 12000,
    precioCompra: 10000,
    utilidad: 2000,
    vendidos: 11,
    owner: "",
  },
]

export const owner = [
  {
    id: 1,
    userName: "david",
    name: "Aramayo Wilber",
  },
]
